### ISSUE TITLE
regex

### ISSUE THREAD

**Issue by ulvido** [canereryol/karekod-parser#1]
öncelikle eline emeğine sağlık. çok güzel bir paket. izninle sadece regex için önerim olacak. regex şemasını çok geniş tutmuşsun. karekod gibi bir meselede daha strict olması gerektiğini düşünüyorum.  (.*) kullanırsan karekod olmayanlar da valid karekod gibi görünüyor. kendi regex şema gruplarım şu şekilde. keza hatam varsa düzeltirsen sevinirim.

shema = {
        "GTIN"            : "(?P<GTIN>01\d{14})",
        "SN"              : "(?P<SN>21[^\W_]{1,20})",
        "XD"              : "(?P<XD>17\d{2}(0[1-9]|1[012])(00|0[1-9]|[12][0-9]|3[01]))",
        "BN"              : "(?P<BN>10[^\W_]{1,20})",
        "NON_ALPHANUMERIC": "[^a-z0-9-]+",
    }

**Comment by canereryol** [comment]
Merhaba. Önerin için teşekkürler. Bu regex i kullandığım yerde karekod doğruluğunu kontrol gibi bir ihtiyacım yoktu. Bundan dolayı geniş bir ifade oldu. Haklısın. Yazdığın regex expression gayet doğru. Emeğine sağlık. En kısa zamanda güncelleyeceğim.

**Comment by ulvido** [comment]
teşekkürler. üstte yazdığım pythondaki bir proje için oluşturduğum regex şemasıydı. js versiyonunda regex için named groups bulamadım ama onu sağlayan bir kütüphane buldum. 

```javascript

"use strict";
const XRegExp = require("xregexp");

const karekod = "010869951412911021A913410C06206794-171902281017C475";

// sondaki x flag, commentlere izin vermesi ve boşlukları görmezden gelmesi için
const shema = XRegExp(`(?<fnc1>
                      ^(01(?<gtin> [0-9]{14}))            #  barkod
                      (21(?<sn>   [a-zA-Z0-9]{1,20}))     #  seri no 
                      ) # fnc1 end
                      (-?)                                #  - varsa reddetmesin
                      (17(?<xd>   (([0-9]{2})(0[1-9]|1[012])(00|0[1-9]|[12][0-9]|3[01]))))  #  miad 
                      (10(?<bn>   [a-zA-Z0-9]{1,20} )) $  #  parti no `, 'x');

// karekodu parçalıyoruz.
const karekodParsed = XRegExp.exec(karekod , shema);

// şimdi parçaları ismiyle çağırabiliriz.
console.log( karekodParsed.gtin );   // 08699514129110
console.log( karekodParsed.bn);     // 17C475 

```

bir de [buradaki](https://www.its.gov.tr/index.php?run=document&download=61) kaynaktan yola çıkarak değişken isimlerini its'ninkiyle aynı yapabilirsin. çünkü zaten kullanacak kişi büyük ihtimal its ile işi olan bir programcı olduğundan its'nin belirlediği zeminde olmak kolaylık sağlar. iyi çalışmalar.

**Comment by canereryol** [comment]
Peki mevcut regex i şöyle güncellesek?
```javascript
var karekodExp = /^010(\d{13})21([^\W_]{1,20})?-17((\d{2})(0[1-9]|1[012])(00|0[1-9]|[12][0-9]|3[01]))10([^\W_]{1,20})/g;
```

> bir de [buradaki](https://www.its.gov.tr/index.php?run=document&download=61) kaynaktan yola çıkarak değişken isimlerini its'ninkiyle aynı yapabilirsin. çünkü zaten kullanacak kişi büyük ihtimal its ile işi olan bir programcı olduğundan its'nin belirlediği zeminde olmak kolaylık sağlar. iyi çalışmalar.

Mantıklı.

**Comment by ulvido** [comment]
evet iş görebilir. sadece ?- değil de -? şeklinde olmalı. 

bi de index.js de pn: kk[6] > pn: kk[7] olcak. yoksa  miadın günü geliyor.

benim yaptığım testlerde bu kadarını görebildim. 

bi de eğer interface i değiştirmeyi göze aldıysan [bu kaynağı](https://www.its.gov.tr/index.php?run=document&download=80) da önermek isterim. iyi çalışmalar.

**Comment by canereryol** [comment]
Versiyon güncellendi.

**Comment by ulvido** [comment]
teşekkürler. elinize sağlık.

**Comment by ulvido** [comment]
# Problem
merhaba. regexte ^ kısmını unutmuşuz. toplu karekod girilen bir textareada false positive alınca fakettim.
aşağıdaki resimdeki örnekte ucuca 3 farklı karaked ucuca ekli ve mevcut regex 1 karekod var gösteriyor. ama metin bu haliyle karekod açısından anlamsız. hiç karekod bulamadım demesi çoklu karekod girdilerinde daha büyük hatalardan kurtarabilir. 

![image](https://github.com/canereryol/karekod-parser/assets/27722274/31eaece6-f06d-4b6e-ad00-008245fcc945)

öte taraftan tekil karekod okutulan yerlerde ise mevcut regex daha avantajlı. karekod okuyucu yanlışlıkla 2-3 kez okusa bile bu haliyle tekil karekodu parse etmeyi başaracak ve kullanıcı hata yapsa bile amacına ulaşacak. o nedenle reopen etmeden comment olarak eklemeyi doğru buldum. ihtiyaca göre şekillendirilebilir.

# Öneri
```
-  /010(\d{13})21([^\W_]{1,20})-?17(\d{2})(0[1-9]|1[012])(00|0[1-9]|[12][0-9]|3[01])10([^\W_]{1,20})$/
+  /^010(\d{13})21([^\W_]{1,20})-?17(\d{2})(0[1-9]|1[012])(00|0[1-9]|[12][0-9]|3[01])10([^\W_]{1,20})$/
```
